# home-manager config for duhsten
# user-level stuff: shell config, git, cli tools etc
{ pkgs, inputs, ... }:

{
  home.username = "duhsten";
  home.homeDirectory = "/home/duhsten";
  home.stateVersion = "25.11";

  home.packages = with pkgs; [
    # cli tools i actually use
    ripgrep
    fd
    bat
    eza
    fzf
    jq
    htop
    tree
    unzip
  ];

  # --- git ---
  programs.git = {
    enable = true;
    settings.user.name  = "duhsten";
    settings.user.email = "duhsten@nixos.local";
  };

  # --- zsh ---
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;

    shellAliases = {
      # nixos shortcuts
      rebuild = "sudo nixos-rebuild switch --flake ~/nixos-config#$(hostname)";
      update   = "nix flake update ~/nixos-config";  # bumps flake.lock to latest
      search   = "nix search nixpkgs";

      # git workflow for the config repo
      # pull latest changes from github before rebuilding on a machine
      cfg-pull = "git -C ~/nixos-config pull";
      # push your changes after editing the config
      cfg-push = "cp ~/.config/DankMaterialShell/settings.json ~/nixos-config/home/configs/DankMaterialShell/settings.json && git -C ~/nixos-config add -A && git -C ~/nixos-config commit -m \"update config\" && git -C ~/nixos-config push";
      # nicer defaults
      ls  = "eza";
      ll  = "eza -l";
      la  = "eza -la";
      cat = "bat -p";
    };

    history = {
      size = 10000;
      save = 10000;
    };
  };

  programs.starship.enable = true;
  programs.fzf.enable = true;

  # niri config — home-manager owns this since niri only reads it, never writes
  # edit the file in ~/nixos-config/home/configs/niri/config.kdl then rebuild
  # (the dms/ includes like colors.kdl are generated by dms, those stay separate)
  xdg.configFile."niri/config.kdl".source = ./configs/niri/config.kdl;

  # set zen as the default browser for all the usual url/html stuff
  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "text/html"                = "zen.desktop";
      "x-scheme-handler/http"   = "zen.desktop";
      "x-scheme-handler/https"  = "zen.desktop";
      "x-scheme-handler/about"  = "zen.desktop";
      "x-scheme-handler/unknown" = "zen.desktop";
    };
  };

  # cursor theme — without this x11/xwayland apps show the ugly default x cursor
  home.pointerCursor = {
    name = "Adwaita";
    package = pkgs.adwaita-icon-theme;
    size = 24;
    x11.enable = true;
    gtk.enable = true;
  };

  programs.home-manager.enable = true;
}
